version: '3.8'

services:
  db:
    image: mysql:8
    container_name: chatbot_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chatbot_network

  django:
    build: .
    image: infospica/chatbot-dev:1.0  # Set the custom image name
    container_name: chatbot_django
    restart: always
    depends_on:
      - db
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - chatbot_network



networks:
  chatbot_network:

volumes:
  mysql_data:
