version: '3.8'

services:
  db:
    image: mysql:8
    container_name: chatbot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatbot_trainer
      MYSQL_USER: ajish
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chatbot_network

  django:
    build: .
    container_name: chatbot_django
    restart: always
    depends_on:
      - db
    ports:
      - "8888:8888"
    environment:
      MYSQL_DATABASE: chatbot_trainer
      MYSQL_USER: ajish
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - .:/app
    networks:
      - chatbot_network

networks:
  chatbot_network:

volumes:
  mysql_data:
