# Generated by Django 5.1.7 on 2025-03-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('user_query', models.TextField()),
                ('response', models.TextField()),
                ('req_token', models.IntegerField()),
                ('res_token', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('filetype', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('request_token', models.IntegerField()),
                ('response_token', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('keywords', models.TextField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.uploadedfile')),
            ],
        ),
    ]
