# Generated by Django 5.1.7 on 2025-03-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_uploadedfile_type_filekeywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='type',
        ),
        migrations.DeleteModel(
            name='FileKeywords',
        ),
    ]
