# Generated by Django 5.1.7 on 2025-03-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_uploadedfile_type_delete_filekeywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='type',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FileKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('keyword', models.CharField(max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.uploadedfile')),
            ],
        ),
    ]
