# Generated by Django 5.1.7 on 2025-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_uploadedfile_type_filekeywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='input_prompt_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='total_token',
            field=models.IntegerField(default=0),
        ),
    ]
