# Generated by Django 5.1.7 on 2025-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chathistory_input_prompt_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='type',
            field=models.BooleanField(default=1),
        ),
    ]
