# Generated by Django 5.1.7 on 2025-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('filetype', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=255)),
                ('request_token', models.IntegerField()),
                ('response_token', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
