# Generated by Django 5.1.7 on 2025-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('user_query', models.TextField()),
                ('response', models.TextField()),
                ('req_token', models.IntegerField()),
                ('res_token', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='filetype',
            field=models.CharField(max_length=255),
        ),
    ]
